title: "Dadaist2 - Metabarcoding analysis from reads to R"
repository: quadram-institute-bioscience/dadaist2
lang: en
description: "dadaist2: toolkit for a complete DADA2 amplicon analysis from the command line"

readme_index:
  with_frontmatter: true

theme: null

remote_theme: jekyllrtdtheme/jekyll-rtd-theme

plugins:
  - jekyll-remote-theme
  - jemoji

markdown: CommonMarkGhPages
commonmark:
  options: ['SMART']
  extensions: ['table']

