name: Darwin-env

# Controls when the action will run. 
on:
  push
    
defaults:
  run:
    # This is needed for miniconda, see:
    # https://github.com/marketplace/actions/setup-miniconda#important.
    shell: bash -l {0}
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install mamba & environment
      uses: mamba-org/provision-with-micromamba@v10

    - name: build meta-packages
      shell: bash -l {0}
      env:
        CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
      run: |
        export MAXICONDA_ENV_RELEASE=${GITHUB_REF##*/}
        conda config --set channel_priority false
        mamba env create -n dadaist --file docs/dadaist2-Darwin.yaml
        conda env export -n dadaist
