# This is a basic workflow to help you get started with Actions

name: Dadaist-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    # This is needed for miniconda, see:
    # https://github.com/marketplace/actions/setup-miniconda#important.
    shell: bash -l {0}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Miniconda
        # You may pin to the exact commit or the version.
        # uses: conda-incubator/setup-miniconda@35d1405e78aa3f784fe3ce9a2eb378d5eeb62169
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          # Conda configuration. Comma separated list of channels to use in order of priority. See https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/ for more information.
          channels: "conda-forge,bioconda,defaults"
          # Experimental. Use mamba as soon as available (either as provided by `mamba-in-installer` or installation by `mamba-version`)
          use-mamba: true
          # Architecture of Miniconda that should be installed. Available options on GitHub-hosted runners are "x86" and "x64". Default is "x64".
          architecture: "x64"
          mamba-version: "*"
      - name: Install requirements.
        run: mamba install -y --only-deps dadaist2
      - name: Test Dadaist
        run: bash test/all.sh
          
        
